### ISSUE TITLE
Not loading local lib dir

### ISSUE THREAD

**Issue by leojrfs** [sapo/digital-signage-server#7]
it doesn't seem to be loading the local lib dir

```
leo@colossus ~/Random/digital-signage-server > python app.py 
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    import utils, bottle
ImportError: No module named utils
```

**Comment by rcarmo** [comment]
You do have to make sure PYTHONPATH is set correctly, which is why we use

https://github.com/sapo/digital-signage-server/blob/master/run.sh

...and a virtualenv, or pyenv.

**Comment by leojrfs** [comment]
so, ive created a env on . ../digital-signage-env as pointed on the script
ive made sure that it runs, but the output is the same

```
leo@colossus ~/Random/digital-signage-server > . ../digital-signage-env/bin/activate
(digital-signage-env)leo@colossus ~/Random/digital-signage-server > python app.py
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    from config import settings
ImportError: cannot import name settings
```

sorry, i am quite new to python and as the Readme does not provide instructions it makes it more difficult

**Comment by hmiguellima** [comment]
Hi Leo,

You need to copy the default settings files "etc/default.json.default
<https://github.com/sapo/digital-signage-server/blob/master/etc/default.json.default>"
and "etc/users.json.default" to new files without the ".default" extension
(e.g. /etc/default.json)

Sorry for the lack in the docs, we'll look into that soon.

Hugo.


2015-01-28 11:31 GMT+00:00 Leo Soares <notifications@github.com>:

**Comment by leojrfs** [comment]
Hi thanks,

ill be more than happy to help with that when i get this working 

now im getting a bunch of pygments related errors when using log  from logkit.py

```
(digital-signage-env)leo@colossus ~/Random/digital-signage-server > ./run.sh 
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    from config import settings
  File "/Users/leo/Random/digital-signage-server/lib/config.py", line 30, in <module>
    log.info("Configuration for %s loaded." % host)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1160, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/Users/leo/Random/digital-signage-server/lib/utils/logkit.py", line 81, in emit
    lexer = guess_lexer(msg)
  File "/Users/leo/Random/digital-signage-env/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 252, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
pygments.util.ClassNotFound: no lexer matching the text found
```

**Comment by Velmont** [comment]
@leojrfs There's a fix for those things in #8.
